apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tsdsystem-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ingv-oe-dev/k8s-tsdsystem.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: tsdsystem

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true