apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tsdsystem-application
  namespace: argocd
spec:
  project: default

  sources:
  - repoURL: https://github.com/ingv-oe-dev/k8s-tsdsystem.git
    targetRevision: sealed-secret
    path: manifests/db/overlays/production
  - repoURL: https://github.com/ingv-oe-dev/k8s-tsdsystem.git
    targetRevision: sealed-secret
    path: manifests/tsd/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: tsdsystem

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    automated:
      selfHeal: true
      prune: true