apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - tsd-deployment.yaml
  - tsd-svc.yaml

namespace: tsdsystem-base

commonLabels:
  app: tsd-base

generatorOptions:
  labels:
    app: tsd-base

configMapGenerator:
- name: tsd-data
  behavior: create
  envs:
    - .env
- name: apache-custom-log
  files:
    - custom-log.conf

secretGenerator:
- name: tsd-secret
  behavior: create
  envs:
  - .env.secret