apiVersion: apps/v1
kind: Deployment
metadata:
  name: tsdsystem-app
  labels:
    app: tsd
spec:
  selector:
    matchLabels:
      app: tsd
  template:
    metadata:
      labels:
        app: tsd
    spec:
      containers:
        - name: tsd-app
          image: ghcr.io/ingv-oe-dev/tsdsystem/tsdsystem-app:v1.4a
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: tsd-data
            - secretRef:
                name: tsd-secret
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /misc/ping
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /misc/ping
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 3
