apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: staging-

namespace: tsdsystem-staging

commonLabels:
  app: tsd-staging

patches:
  - path: tsd-deployment-patch.yaml
    target:
      kind: Deployment
      name: tsdsystem-app
  - path: tsd-ingress-patch.yaml
    target:
      kind: Ingress
      name: tsd-ingress

images:
  - name: ghcr.io/ingv-oe-dev/tsdsystem/tsdsystem-app
    newTag: v1.7a

generatorOptions:
  labels:
    app: tsd-staging
  disableNameSuffixHash: true

configMapGenerator:
- name: tsd-data
  namespace: tsdsystem-staging
  behavior: replace
  literals:
    - DB_HOST=staging-tsdsystem-db-svc
    - DB_PORT=5432
    - APP_ALLOWED_HOSTS=*
    - ENV=production

secretGenerator:
- name: tsd-secret
  behavior: replace
  envs:
  - .env.secret