apiVersion: apps/v1
kind: Deployment
metadata:
  name: tsdsystem-app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: tsd-app
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"