apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - sealed-secret.yaml

namespace: tsdsystem

commonLabels:
  app: tsd

patches:
  - path: tsd-deployment-patch.yaml
    target:
      kind: Deployment
      name: tsdsystem-app
  - path: tsd-ingress-patch.yaml
    target:
      kind: Ingress
      name: tsd-ingress

images:
  - name: ghcr.io/ingv-oe-dev/tsdsystem/tsdsystem-app
    newTag: v1.7a

generatorOptions:
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
  labels:
    app: tsd
  disableNameSuffixHash: true

configurations:
  - sealed-secret-config.yaml

configMapGenerator:
- name: tsd-data
  namespace: tsdsystem
  behavior: create
  literals:
    - DB_HOST=tsdsystem-db-svc
    - DB_PORT=5432
    - APP_ALLOWED_HOSTS=*
    - ENV=production

secretGenerator:
- name: tsd-secret
  type: Opaque
  options:
    annotations:
      config.kubernetes.io/local-config: "true"
  behavior: replace
