apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: staging-

namespace: tsdsystem-staging

commonLabels:
  app: db-staging

patches:
  - path: timescale-ss-patch.yaml
    target:
      kind: StatefulSet
      name: tsdsystem-db

generatorOptions:
  labels:
    app: db-base
  disableNameSuffixHash: true

configMapGenerator:
- name: tsd-db-data
  behavior: replace
  envs:
  - .env

secretGenerator:
- name: tsd-db-secret
  behavior: replace
  envs:
  - .env.secret