apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - sealed-secret.yaml

namespace: tsdsystem

commonLabels:
  app: db

patches:
  - path: timescale-ss-patch.yaml
    target:
      kind: StatefulSet
      name: tsdsystem-db

images:
  - name: ghcr.io/ingv-oe-dev/tsdsystem/tsdsystem-db
    newTag: v1.5a

generatorOptions:
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
  labels:
    app: db
  disableNameSuffixHash: true

configurations:
  - sealed-secret-config.yaml

secretGenerator:
- name: tsd-db-secret
  type: Opaque
  options:
      annotations:
        config.kubernetes.io/local-config: "true"
  behavior: replace
