apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - timescale-ss.yaml
  - timescale-svc.yaml

namespace: tsdsystem-base

commonLabels:
  app: db-base

generatorOptions:
  labels:
    app: db-base

configMapGenerator:
- name: tsd-db-data
  behavior: create
  envs:
  - .env

secretGenerator:
- name: tsd-db-secret
  behavior: create
  envs:
  - .env.secret