apiVersion: v1
kind: Service
metadata:
  name: tsdsystem-db-svc
  labels:
    app: db
spec:
  ports:
    - name: db
      port: 5432
      targetPort: postgres
  selector:
    app: db
  clusterIP: None
